// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwS7ZJja9_x8CHtqsM9okEh5Kd91xC6cs',
    appId: '1:95599106309:web:bb6ddd61433dfb7e53bf6c',
    messagingSenderId: '95599106309',
    projectId: 'ebook-2a423',
    authDomain: 'ebook-2a423.firebaseapp.com',
    storageBucket: 'ebook-2a423.appspot.com',
    measurementId: 'G-QKL1NGB8XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEpy1H7WqufGRZVnZB2ZYMtbjvz6jfao',
    appId: '1:95599106309:android:b1a04bc7a644d2f153bf6c',
    messagingSenderId: '95599106309',
    projectId: 'ebook-2a423',
    storageBucket: 'ebook-2a423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjyDvVLCK_dlexdE4wqFGF3FeS6DnbQc',
    appId: '1:95599106309:ios:ed3bfb2c57ebc87253bf6c',
    messagingSenderId: '95599106309',
    projectId: 'ebook-2a423',
    storageBucket: 'ebook-2a423.appspot.com',
    iosBundleId: 'com.example.flutterEbookWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjyDvVLCK_dlexdE4wqFGF3FeS6DnbQc',
    appId: '1:95599106309:ios:187c0566803b4e9353bf6c',
    messagingSenderId: '95599106309',
    projectId: 'ebook-2a423',
    storageBucket: 'ebook-2a423.appspot.com',
    iosBundleId: 'com.example.flutterEbookWebsite.RunnerTests',
  );
}
